### ISSUE TITLE
LoadError on step 3 of installation

### ISSUE THREAD

**Issue by geetrk** [NetsoftHoldings/HubstaffExportTool#1]
[https://support.hubstaff.com/export-screenshots/](url) - At step 3
![screenshot 317](https://user-images.githubusercontent.com/26969039/37095777-d3236bd2-223c-11e8-8dc7-099bfcc2dd51.png) - This is the error (No such file or directory -- hubstaff-export.rb LoadError)

**Step 3:** ruby hubstaff-export.rb authenticate AppToken bob@example.com MyAwesomePass

**Comment by urkle** [comment]
you need to run the ruby in the same folder that you downloaded the HubstaffExport repository.  As it is looking for the "hubstaff-export.rb" in the current folder.

**Comment by geetrk** [comment]
Thanks. It worked.
